In [3]:
from bs4 import BeautifulSoup
import requests
import numpy as np
import pandas as pd

In [3]:
try:
    while True:
        index = 1
        base_url = f"https://www.imdb.com/search/title/?country_of_origin=ph&start={index}"
        src = requests.get(base_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})
        soup = BeautifulSoup(src.content, 'lxml')
        divs = soup.find_all('div', {'class':'lister-item mode-advanced'})
except:

In [28]:
index = 1
base_url = f"https://www.imdb.com/search/title/?country_of_origin=ph&start={index}"
src = requests.get(base_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})
soup = BeautifulSoup(src.content, 'lxml')
content = soup.find_all('h3', {'class':'lister-item-header'})

for item in content:
    titles = item.find('a').text
    years = item.find_all('span')[1].text
    print(titles, years)


The Big Bird Cage (1972)
Miracle in Cell No. 7 (2019)
Black Mama White Mama (1973)
Hello, Stranger: The Movie (2021)
Yellow Rose (I) (2019)
Eerie (2018)
Women in Cages (1971)
Wonder Women (1973)
Anak ng Macho Dancer (2021)
The Big Doll House (1971)
Hello, Stranger (2020)
The House Arrest of Us (2020–2021)
Raw Force (1982)
Maria (II) (2019)
Just a Stranger (2019)
Gaya sa pelikula (2020– )
Cuddle Weather (2019)
www.XXX.com (2003)
U-Turn (2020)
BuyBust (2018)
Adan (2019)
Gameboys (2020– )
The Panti Sisters (2019)
Must Be... Love (2013)
Wheels of Fire (1985)
Watch List (2019)
Paglaki ko, gusto kong maging pornstar (2021)
Sex Drive (2003)
Always Be My Maybe (2016)
Manila in the Claws of Light (1975)
F#*@bois (2019)
On the Wings of Love (2015–2016)
Can't Help Falling in Love (2017)
My Neighbor's Wife (2011)
The Hows of Us (2018)
TNT Jackson (1974)
The Mistress (I) (2012)
Stryker (1983)
Ang babaeng humayo (2016)
Hello, Love, Goodbye (2019)
Dahil mahal na mahal kita (1998)
Rigodon (2012)
Beyon

In [18]:
content[0]

<h3 class="lister-item-header">
<span class="lister-item-index unbold text-primary">1.</span>
<a href="/title/tt0068273/?ref_=adv_li_tt">The Big Bird Cage</a>
<span class="lister-item-year text-muted unbold">(1972)</span>
</h3>

In [5]:
tab_tag = soup.find_all('table', {'class':'wikitable'})
len(tab_tag)

10

In [6]:
lst = []

In [7]:
df = pd.DataFrame()

In [8]:
count = np.arange(10)
print(count)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
for i in count:
    tab_ = pd.read_html(str(tab_tag[i]))
    df_ = pd.DataFrame(tab_[0])
    df = pd.concat([df, df_], axis = 0)

In [10]:
movie_title = [x for x in df['Title']]

In [11]:
movie_title.remove('2000')
movie_title.remove('2001')
movie_title.remove('2002')
movie_title.remove('2003')
movie_title.remove('2004')
movie_title.remove('2005')
movie_title.remove('2006')
movie_title.remove('2007')
movie_title.remove('2008')
movie_title.remove('2009')

In [12]:
# movie_title

In [13]:
# 2010

In [14]:
base_ten_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2010"

In [15]:
src = requests.get(base_ten_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [16]:
soup = BeautifulSoup(src.content, 'lxml')

In [17]:
tab_ten = soup.find_all('table', {'class':'wikitable'})

In [18]:
df_ = pd.read_html(str(tab_ten[0]))
df_ten = pd.DataFrame(df_[0])

In [19]:
ten_list = [x for x in df_ten['Title']]
movie_title = movie_title + ten_list

In [20]:
movie_title[:10]

['Abandonada',
 'Akin Ang Labang Ito',
 'Anak',
 'Ang Dalubhasa',
 'Anghel Dela Guardia',
 'Arayyy!',
 'Baliktaran',
 'Basta Tricycle Driver... Sweet Lover',
 'Birthday Gift 2',
 'Biyaheng Langit']

In [21]:
# 2011

In [22]:
base_ele_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2011"

In [23]:
src = requests.get(base_ele_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [24]:
soup = BeautifulSoup(src.content, 'lxml')

In [25]:
tab_ele = soup.find_all('table', {'class':'wikitable'})

In [26]:
df_ = pd.read_html(str(tab_ele[1]))
df_ele = pd.DataFrame(df_[0])

In [27]:
ele_list = [x for x in df_ele['Title']]
movie_title = movie_title + ele_list

In [28]:
movie_title[-10:]

['Third World Happy',
 'Tum: My Pledge of Love',
 'Tween Academy: Class of 2012',
 'Tumbok',
 'Way Back Home',
 'Wedding Tayo, Wedding Hindi',
 "Who's That Girl",
 "Won't Last A Day Without You",
 'Yesterday, Today, Tomorrow',
 'Zombadings 1: Patayin sa Shokot si Remington']

In [29]:
# 2012

In [30]:
base_twl_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2012"

In [31]:
src = requests.get(base_twl_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [32]:
soup = BeautifulSoup(src.content, 'lxml')

In [33]:
tab_twl = soup.find_all('table', {'class':'wikitable'})

In [34]:
count_ = np.arange(1,5)

In [35]:
df_s = pd.DataFrame()

In [36]:
print(count_)

[1 2 3 4]


In [37]:
for i in count_:
    tab_ = pd.read_html(str(tab_twl[i]))
    df_ = pd.DataFrame(tab_[0])
    #print(df_)
    df_s = pd.concat([df_s, df_], axis = 0)

In [38]:
twl_list = [x for x in df_s['Title']]

In [39]:
movie_title += twl_list

In [40]:
movie_title[-10:]

['Flames of Love',
 'MNL 143',
 'Si Agimat, Si Enteng, at Si Ako',
 'El Presidente',
 'One More Try',
 'Shake, Rattle & Roll 14',
 'Sisterakas',
 'Sosy Problems',
 'The Strangers',
 'Thy Womb']

In [41]:
# 2013

In [42]:
base_trt_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2013"

In [43]:
src = requests.get(base_trt_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [44]:
soup = BeautifulSoup(src.content, 'lxml')

In [45]:
tab_trt = soup.find_all('table', {'class':'wikitable'})

In [46]:
count_ = np.arange(1,5)

In [47]:
df_s = pd.DataFrame()

In [48]:
print(count_)

[1 2 3 4]


In [49]:
for i in count_:
    tab_ = pd.read_html(str(tab_trt[i]))
    df_ = pd.DataFrame(tab_[0])
    #print(df_)
    df_s = pd.concat([df_s, df_], axis = 0)

In [50]:
trt_list = [x for x in df_s['Title']]

In [51]:
movie_title += trt_list

In [52]:
movie_title[-10:]

['How to Disappear Completely1',
 'Boogie1',
 'Girl, Boy, Bakla, Tomboy',
 'My Little Bossings',
 'Kimmy Dora: Ang Kiyemeng Prequel',
 'Pagpag: Siyam na Buhay',
 '10,000 Hours',
 'Pedro Calungsod: Batang Martir',
 'Boy Golden: Shoot to Kill, the Arturo Porcuna Story',
 'Kaleidoscope World']

In [53]:
# 2014

In [54]:
base_frt_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2014"

In [55]:
src = requests.get(base_frt_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [56]:
soup = BeautifulSoup(src.content, 'lxml')

In [57]:
tab_frt = soup.find_all('table', {'class':'wikitable'})

In [58]:
count_ = np.arange(1,5)

In [59]:
df_s = pd.DataFrame()

In [60]:
print(count_)

[1 2 3 4]


In [61]:
for i in count_:
    tab_ = pd.read_html(str(tab_frt[i]))
    df_ = pd.DataFrame(tab_[0])
    #print(df_)
    df_s = pd.concat([df_s, df_], axis = 0)

In [62]:
frt_list = [x for x in df_s['Title']]

In [63]:
movie_title += frt_list

In [64]:
movie_title[-10:]

['Mulat',
 'Gangster Lolo',
 'Bonifacio: Ang Unang Pangulo',
 'English Only, Please',
 'Feng Shui 2',
 'Kubot: The Aswang Chronicles 2',
 'Magnum Muslim.357',
 'My Big Bossing',
 'The Amazing Praybeyt Benjamin',
 'Shake, Rattle & Roll XV']

In [65]:
# 2015

In [66]:
base_frt_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2015"

In [67]:
src = requests.get(base_frt_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [68]:
soup = BeautifulSoup(src.content, 'lxml')

In [69]:
tab_ftn = soup.find_all('table', {'class':'wikitable'})

In [70]:
count_ = np.arange(1,5)

In [71]:
df_s = pd.DataFrame()

In [72]:
print(count_)

[1 2 3 4]


In [73]:
for i in count_:
    tab_ = pd.read_html(str(tab_ftn[i]))
    df_ = pd.DataFrame(tab_[0])
    #print(df_)
    df_s = pd.concat([df_s, df_], axis = 0)

In [74]:
ftn_list = [x for x in df_s['Title']]

In [75]:
movie_title += ftn_list

In [76]:
movie_title[-10:]

['Toto',
 'Turo-Turo',
 'All You Need Is Pag-Ibig',
 'Beauty and the Bestie',
 'Buy Now, Die Later',
 'Haunted Mansion',
 'Honor Thy Father',
 'My Bebe Love: #KiligPaMore',
 'Nilalang',
 '#Walang Forever']

In [77]:
# 2016

In [78]:
base_frt_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2016"

In [79]:
src = requests.get(base_frt_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [80]:
soup = BeautifulSoup(src.content, 'lxml')

In [81]:
tab_sx = soup.find_all('table', {'class':'wikitable'})

In [82]:
count_ = np.arange(1,5)

In [83]:
df_s = pd.DataFrame()

In [84]:
print(count_)

[1 2 3 4]


In [85]:
for i in count_:
    tab_ = pd.read_html(str(tab_sx[i]))
    df_ = pd.DataFrame(tab_[0])
    #print(df_)
    df_s = pd.concat([df_s, df_], axis = 0)

In [86]:
sx_list = [x for x in df_s['Title']]

In [87]:
movie_title += sx_list

In [88]:
movie_title[-10:]

['Enteng Kabisote 10 and the Abangers',
 'Mano Po 7: Tsinoy',
 'Ang Babae sa Septic Tank 2: #ForeverIsNotEnough',
 'Die Beautiful',
 'Kabisera',
 'Oro',
 'Saving Sally',
 'Seklusyon',
 'Sunday Beauty Queen',
 'Vince & Kath & James']

In [89]:
# 2017

In [90]:
base_svt_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2017"

In [91]:
src = requests.get(base_svt_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [92]:
soup = BeautifulSoup(src.content, 'lxml')

In [93]:
tab_svt = soup.find_all('table', {'class':'wikitable'})

In [94]:
count_ = np.arange(1,5)

In [95]:
df_s = pd.DataFrame()

In [96]:
print(count_)

[1 2 3 4]


In [97]:
for i in count_:
    tab_ = pd.read_html(str(tab_svt[i]))
    df_ = pd.DataFrame(tab_[0])
    #print(df_)
    df_s = pd.concat([df_s, df_], axis = 0)

In [98]:
svt_list = [x for x in df_s['Title']]

In [99]:
movie_title += svt_list

In [100]:
movie_title[-10:]

['Kamandag ng Droga',
 'Smaller and Smaller Circles',
 'All of You',
 'Deadma Walking',
 'Gandarrapiddo: The Revenger Squad',
 'Haunted Forest',
 'Ang Larawan',
 'Meant to Beh',
 'Ang Panday',
 'Siargao']

In [101]:
# 2018

In [102]:
base_eth_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2018"

In [103]:
src = requests.get(base_eth_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [104]:
soup = BeautifulSoup(src.content, 'lxml')

In [105]:
tab_eth = soup.find_all('table', {'class':'wikitable'})

In [106]:
count_ = np.arange(1,5)

In [107]:
df_s = pd.DataFrame()

In [108]:
print(count_)

[1 2 3 4]


In [109]:
for i in count_:
    tab_ = pd.read_html(str(tab_eth[i]))
    df_ = pd.DataFrame(tab_[0])
    #print(df_)
    df_s = pd.concat([df_s, df_], axis = 0)

In [110]:
eth_list = [x for x in df_s['Title']]

In [111]:
movie_title += eth_list

In [112]:
movie_title[-10:]

['Kahit Ayaw Mo Na',
 'Everybody Loves Baby Wendy',
 'Aurora',
 'Fantastica: The Princesses, The Prince and The Perya',
 'The Girl in the Orange Dress',
 'Jack Em Popoy: The Puliscredibles',
 'Mary, Marry Me',
 'One Great Love',
 'Otlum',
 "Rainbow's Sunset"]

In [113]:
# 2019

In [114]:
base_nth_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2019"

In [115]:
src = requests.get(base_nth_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [116]:
soup = BeautifulSoup(src.content, 'lxml')

In [117]:
tab_nth = soup.find_all('table', {'class':'wikitable'})

In [118]:
count_ = np.arange(1,5)

In [119]:
df_s = pd.DataFrame()

In [120]:
print(count_)

[1 2 3 4]


In [121]:
for i in count_:
    tab_ = pd.read_html(str(tab_nth[i]))
    df_ = pd.DataFrame(tab_[0])
    #print(df_)
    df_s = pd.concat([df_s, df_], axis = 0)

In [122]:
nth_list = [x for x in df_s['Title']]

In [123]:
movie_title += nth_list

In [124]:
movie_title[-10:]

['Sunod',
 'Miracle in Cell No.7',
 'Mission Unstapabol: The Don Identity',
 'The Mall, The Merrier',
 'Mindanao',
 '3pol Trobol: Huli Ka Balbon',
 'Culion',
 'Write About Love',
 nan,
 nan]

In [125]:
# 2020

In [126]:
base_twy_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2020"

In [127]:
src = requests.get(base_twy_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [128]:
soup = BeautifulSoup(src.content, 'lxml')

In [129]:
tab_twy = soup.find_all('table', {'class':'wikitable'})

In [130]:
count_ = np.arange(1,5)

In [131]:
df_s = pd.DataFrame()

In [132]:
print(count_)

[1 2 3 4]


In [133]:
for i in count_:
    tab_ = pd.read_html(str(tab_twy[i]))
    df_ = pd.DataFrame(tab_[0])
    #print(df_)
    df_s = pd.concat([df_s, df_], axis = 0)

In [134]:
twy_list = [x for x in df_s['Title']]

In [135]:
movie_title += twy_list

In [136]:
movie_title[-10:]

['Coming Home',
 'Fan Girl',
 'Isa Pang Bahaghari',
 'Magikland',
 'Mang Kepweng: Ang Lihim ng Bandanang Itim',
 'Pakboys Takusa',
 'Suarez: The Healing Priest',
 'Tagpuan',
 'The Boy Foretold by the Stars',
 'The Missing']

In [137]:
# complete list of movie 2000 to 2020

In [138]:
len(movie_title)

1322

In [139]:
len(set(movie_title)) # why does the number of movies became smaller? similar titles? 

1305

In [143]:
movie_title[-5:]

['Pakboys Takusa',
 'Suarez: The Healing Priest',
 'Tagpuan',
 'The Boy Foretold by the Stars',
 'The Missing']

In [145]:
pd.DataFrame(movie_title).to_csv('movie_titles.csv')