In [1]:
from bs4 import BeautifulSoup
import requests
import numpy as np
import pandas as pd

In [2]:
base_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_the_2000s"

In [3]:
src = requests.get(base_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})

In [4]:
soup = BeautifulSoup(src.content, 'lxml')

In [5]:
tab_tag = soup.find_all('table', {'class':'wikitable'})
len(tab_tag)

10

In [6]:
lst = []

In [7]:
df = pd.DataFrame()

In [8]:
count = np.arange(10)
print(count)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
for i in count:
    tab_ = pd.read_html(str(tab_tag[i]))
    df_ = pd.DataFrame(tab_[0])
    df = pd.concat([df, df_], axis = 0)

In [10]:
movie_title = [x for x in df['Title']]

In [11]:
df.reset_index(inplace=True)
df

index                                      Title             Director  \
0        0                                       2000                 2000   
1        1                                 Abandonada        Joel Lamangan   
2        2                        Akin Ang Labang Ito          Baldo Marro   
3        3                                       Anak      Rory B. Quintos   
4        4                              Ang Dalubhasa    Fernando Poe, Jr.   
..     ...                                        ...                  ...   
370     44                             Wanted: Border        Ray Gibraltar   
371     45                                   Wapakman            Topel Lee   
372     46                               When I Met U        Joel Lamangan   
373     47  Yaya and Angelina: The Spoiled Brat Movie         Mike Tuviera   
374     48                        You Changed My Life  Cathy Garcia-Molina   

                                                  Cast             Genre  \
0                                                 2000              2000   
1         Maricel Soriano, Edu Manzano, Angelu De Leon             Drama   
2    Ace Espinosa, Eddie Gutierrez, Ynez Veneracion...            Action   
3                      Vilma Santos, Claudine Barretto             Drama   
4    Fernando Poe, Jr., Nanette Medved, Maritoni Fe...            Action   
..                                                 ...               ...   
370                                      Rosanna Roces  Horror, thriller   
371        Manny Pacquiao, Krista Ranillo, Bianca King           Fantasy   
372                   KC Concepcion, Richard Gutierrez           Romance   
373                            Ogie Alcasid, Michael V            Comedy   
374                    John Lloyd Cruz, Sarah Geronimo           Romance   

                                Studio  Unnamed: 5  Unnamed: 6  
0                                 2000      2000.0      2000.0  
1                           Viva Films         NaN         NaN  
2                          ATB-4 Films         NaN         NaN  
3                          Star Cinema         NaN         NaN  
4                    Millennium Cinema         NaN         NaN  
..                                 ...         ...         ...  
370               Cinema One Originals         NaN         NaN  
371                Solar Entertainment         NaN         NaN  
372  GMA Films and Regal Entertainment         NaN         NaN  
373    GMA Films and APT Entertainment         NaN         NaN  
374         Star Cinema and Viva Films         NaN         NaN  

[375 rows x 8 columns]

In [12]:
years = np.arange(2000,2010)

In [13]:
years

array([2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009])

In [14]:
df.Year = 0

In [15]:
# create year column
for year in years:
    if year == 2009:
        nidx = df.iloc[-1].name + 1
    else:
        nidx = df.loc[df.Title == str(year+1)].index[0]
    idx = df.loc[df.Title == str(year)].index[0]
    df.loc[idx:nidx, 'Year'] = year

In [16]:
df = df[['Title', 'Director', 'Year']]
df.dropna(subset=['Title'], inplace=True)
df.drop_duplicates(subset=['Title'], inplace=True)

<ipython-input-16-ccef38b6ef34>:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.dropna(subset=['Title'], inplace=True)
<ipython-input-16-ccef38b6ef34>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(subset=['Title'], inplace=True)


In [17]:
df

Title             Director    Year
0                                         2000                 2000  2000.0
1                                   Abandonada        Joel Lamangan  2000.0
2                          Akin Ang Labang Ito          Baldo Marro  2000.0
3                                         Anak      Rory B. Quintos  2000.0
4                                Ang Dalubhasa    Fernando Poe, Jr.  2000.0
..                                         ...                  ...     ...
370                             Wanted: Border        Ray Gibraltar  2009.0
371                                   Wapakman            Topel Lee  2009.0
372                               When I Met U        Joel Lamangan  2009.0
373  Yaya and Angelina: The Spoiled Brat Movie         Mike Tuviera  2009.0
374                        You Changed My Life  Cathy Garcia-Molina  2009.0

[370 rows x 3 columns]

In [18]:
# drop year rows
for year in years:
    idx = df.loc[df.Title == str(year)].index[0]
    df.drop([idx], inplace=True)
df.reset_index(inplace=True, drop=True)
df

c:\users\eric\scoop\apps\miniconda3\current\lib\site-packages\pandas\core\frame.py:4305: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


Title             Director    Year
0                                   Abandonada        Joel Lamangan  2000.0
1                          Akin Ang Labang Ito          Baldo Marro  2000.0
2                                         Anak      Rory B. Quintos  2000.0
3                                Ang Dalubhasa    Fernando Poe, Jr.  2000.0
4                          Anghel Dela Guardia      William G. Mayo  2000.0
..                                         ...                  ...     ...
355                             Wanted: Border        Ray Gibraltar  2009.0
356                                   Wapakman            Topel Lee  2009.0
357                               When I Met U        Joel Lamangan  2009.0
358  Yaya and Angelina: The Spoiled Brat Movie         Mike Tuviera  2009.0
359                        You Changed My Life  Cathy Garcia-Molina  2009.0

[360 rows x 3 columns]

In [19]:
df.to_csv('movies_2000s.csv', index=False)

In [20]:
years = np.arange(2010, 2012)

In [21]:
base_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_"

# 2010, 2011
for year in years:
    src = requests.get(base_url + str(year), headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})
    soup = BeautifulSoup(src.content, 'lxml')
    tab_ten = soup.find_all('table', {'class':'wikitable'})
    df_ = pd.read_html(str(tab_ten))
    if year == 2010:
        df_ten = pd.DataFrame(df_[0])
    elif year == 2011:
        df_ten = pd.DataFrame(df_[1])
    df_ten.dropna(subset=['Title'], inplace=True)
    df_ten.drop_duplicates(subset=['Title'], inplace=True)
    df_ten = df_ten[['Title', 'Director']]
    df_ten['Year'] = year
    df_ten.to_csv(f'movies_{str(year)}.csv', index=False)

In [22]:
# 2012
base_twl_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2012"
src = requests.get(base_twl_url, headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})
soup = BeautifulSoup(src.content, 'lxml')
tab_twl = soup.find_all('table', {'class':'wikitable'})
count_ = np.arange(1,5)
df_merged = pd.DataFrame()
for i in count_:
    tab_ = pd.read_html(str(tab_twl[i]))
    df_ = pd.DataFrame(tab_[0])
    df_merged = pd.concat([df_merged, df_], axis = 0)

df_merged.dropna(subset=['Title'], inplace=True)
df_merged.drop_duplicates(subset=['Title'], inplace=True)

df_merged = df_merged[['Title', 'Production company']]
df_merged.rename(columns={"Production company": "Director"}, inplace=True)
df_merged['Year'] = 2012
df_merged.to_csv('movies_2012.csv', index=False)

df_merged

Title  \
0                                A Mother's Story   
1                                 My Cactus Heart   
2                                       Pintakasi   
3                              ÜnOfficially Yours   
4                                          Hitman   
5                       Corazon: Ang Unang Aswang   
6                              My Kontrabida Girl   
7                                     The Witness   
0                     Moron 5 and the Crying Lady   
1                                          Busong   
2                               The Mommy Returns   
3                             Every Breath U Take   
4                                Born To Love You   
5                          Boy Pick-Up: The Movie   
6             Kimmy Dora and The Temple of Kiyeme   
0                                     The Healing   
1                                           Posas   
2                                 Just One Summer   
3                                     The Reunion   
4                             Mga Mumunting Lihim   
5                                       Guni-Guni   
6                                         Amorosa   
7               I Do Bidoo Bidoo: Heto nAPO Sila!   
8                                         Captive   
9                                          Bwakaw   
10                                   Ang Nawawala   
11                                   The Mistress   
12                                      Graceland   
13                                      Pridyider   
14                                        Biktima   
15                              Of All the Things   
16                                     Santa Niña   
0                                Give Up Tomorrow   
1                 This Guy's in Love with U Mare!   
2                   Tiktik: The Aswang Chronicles   
3                                 A Secret Affair   
4                             Suddenly It's Magic   
5   Six Degrees of Separation from Lilia Cuntapay   
6                    Madaling Araw, Mahabang Gabi   
7                                    24/7 in Love   
8                                         Rigodon   
9                 D' Kilabots Pogi Brothers Weh?!   
10                                        Supremo   
11                                       Boundary   
12                                 Flames of Love   
13                                        MNL 143   
14                Si Agimat, Si Enteng, at Si Ako   
15                                  El Presidente   
16                                   One More Try   
17                        Shake, Rattle & Roll 14   
18                                     Sisterakas   
19                                  Sosy Problems   
20                                  The Strangers   
21                                       Thy Womb   

                                             Director  Year  
0                                     John D. Lazatin  2012  
1                                       Enrico Santos  2012  
2                                           Lee Meily  2012  
3                                 Cathy Garcia-Molina  2012  
4                                       Cesar Montano  2012  
5                                       Richard Somes  2012  
6                                         Jade Castro  2012  
7                                      Muhammad Yusuf  2012  
0                                     Wenn V. Deramas  2012  
1                                      Auraeus Solito  2012  
2                                       Joel Lamangan  2012  
3                                    Mae Czarina Cruz  2012  
4                                      Jerome Pabocan  2012  
5                                      Dominic Zapata  2012  
6                                        Joyce Bernal  2012  
0                                          Chito Rono  2012  
1                                    Lawrence Fajardo  2012  
2           

In [48]:
from urllib.request import urlopen

base_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_2013"

# 2013
page = urlopen(base_url)
page_content = page.read()
with open('2013.html', 'wb') as fid:
    fid.write(page_content)

In [49]:
with open('2013.html', 'rb') as html:
    soup = BeautifulSoup(html, 'html.parser')
    tab_trt = soup.find_all('table', {'class':'wikitable'})
    count_ = np.arange(1,5)
    df_merged = pd.DataFrame()
    for i in count_:
        tab_ = pd.read_html(str(tab_trt[i]))
        df_ = pd.DataFrame(tab_[0])
        df_merged = pd.concat([df_merged, df_], axis = 0)
    df_merged.dropna(subset=['Title'], inplace=True)
    df_merged.drop_duplicates(subset=['Title'], inplace=True)
    df_merged = df_merged[df_merged['Cast and crew'].str.contains('Director')]
    df_merged['Director'] = df_merged['Cast and crew'].map(lambda s: s.split(' (Director')[0])
    df_merged = df_merged[['Title', 'Director']]
    df_merged['Year'] = 2013
    df_merged.to_csv(f'movies_2013.csv', index=False)

In [50]:
years = np.arange(2014, 2021)
years

array([2014, 2015, 2016, 2017, 2018, 2019, 2020])

In [24]:
# 2014 - 2020

for year in years:
    base_url = "https://en.wikipedia.org/wiki/List_of_Philippine_films_of_"
    src = requests.get(base_url + str(year), headers = {'User-Agent':'Mozilla/5.0 (X11; Linux)'})
    soup = BeautifulSoup(src.content, 'lxml')
    tab_trt = soup.find_all('table', {'class':'wikitable'})
    count_ = np.arange(1,5)
    df_merged = pd.DataFrame()
    for i in count_:
        tab_ = pd.read_html(str(tab_trt[i]))
        df_ = pd.DataFrame(tab_[0])
        df_merged = pd.concat([df_merged, df_], axis = 0)
    df_merged.dropna(subset=['Title'], inplace=True)
    df_merged.drop_duplicates(subset=['Title'], inplace=True)
    #director
    df_merged = df_merged[df_merged['Cast and crew'].str.contains('director')]
    df_merged['Director'] = df_merged['Cast and crew'].map(lambda s: s.split(' (director')[0])
    df_merged = df_merged[['Title', 'Director']]
    df_merged['Year'] = year
    df_merged.to_csv(f'movies_{str(year)}.csv', index=False)

In [ ]:
def splitByDirector(coluin):
    asdnflsdkfjkj